# Generated by Django 4.0.7 on 2023-05-30 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pessoa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('responsavel', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('cliente', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda_core.agenda')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='lista_tarefas',
            field=models.ManyToManyField(related_name='agendas', to='agenda_core.tarefa'),
        ),
    ]
